/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package mobi.playeoj.android;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int biolith=0x7f020000;
        public static final int card=0x7f020001;
        public static final int earth=0x7f020002;
        public static final int fire=0x7f020003;
        public static final int icon=0x7f020004;
        public static final int none=0x7f020005;
        public static final int spell=0x7f020006;
        public static final int water=0x7f020007;
        public static final int wood=0x7f020008;
    }
    public static final class id {
        public static final int card_activation_cost=0x7f050004;
        public static final int card_description=0x7f050006;
        public static final int card_element=0x7f050002;
        public static final int card_race=0x7f050005;
        public static final int card_summoning_cost=0x7f050003;
        public static final int card_title=0x7f050001;
        public static final int webview=0x7f050000;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int main=0x7f030001;
        public static final int show_card=0x7f030002;
    }
    public static final class string {
        public static final int about=0x7f040007;
        /**  Menu Options 
         */
        public static final int all_cards=0x7f040002;
        public static final int app_name=0x7f040001;
        public static final int by_affiliation=0x7f040005;
        public static final int by_element=0x7f040003;
        public static final int by_race=0x7f040004;
        /**  Show Card 
         */
        public static final int card_name=0x7f040008;
        public static final int glossary=0x7f040006;
        public static final int hello=0x7f040000;
    }
}
